"""Read-only fixed-endpoint HTTP with a finite budget, circuit breaker and bounded bodies."""
import json
import time
from urllib.request import Request, build_opener, HTTPRedirectHandler
from .registry import PROVIDERS

class Deferred(ValueError): pass

class NoRedirect(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        raise ValueError('redirect rejected')

class Transport:
    def __init__(self, max_calls=1200, seconds=360, timeout=6):
        self.max_calls=max_calls; self.deadline=time.monotonic()+seconds; self.timeout=timeout
        self.calls=0; self.failures={}; self.contexts={}; self.last_request={}; self.opener=build_opener(NoRedirect())
        self.allowed={url for ps in PROVIDERS.values() for _,url in ps}

    def request(self,base,path='',payload=None,validate=None):
        if base not in self.allowed or (path and not path.startswith(('/', '?'))):
            raise ValueError('endpoint outside allowlist')
        # Paths are only generated by adapters; never follow provider-returned URLs.
        if '://' in path or '..' in path: raise ValueError('invalid endpoint path')
        if self.calls>=self.max_calls or time.monotonic()>=self.deadline:
            raise Deferred('request/time budget exhausted')
        if self.failures.get(base,0)>=3: raise Deferred('provider circuit open after 3 consecutive failures')
        interval=1.0 if base=='https://api.trongrid.io' else 0.4 if base.endswith('.drpc.org') else 0
        remaining=interval-(time.monotonic()-self.last_request.get(base,float('-inf')))
        if remaining>0:
            if time.monotonic()+remaining>=self.deadline: raise Deferred('request/time budget exhausted during rate wait')
            time.sleep(remaining)
            if time.monotonic()>=self.deadline: raise Deferred('request/time budget exhausted during rate wait')
        self.last_request[base]=time.monotonic()
        self.calls+=1
        data=None if payload is None else json.dumps(payload).encode()
        req=Request(base+path,data=data,headers={'Content-Type':'application/json',
            'User-Agent':'sanctions-watch-public-chain/1'})
        try:
            with self.opener.open(req,timeout=min(self.timeout,max(0.1,self.deadline-time.monotonic()))) as resp:
                raw=resp.read(512*1024+1)
                if len(raw)>512*1024: raise ValueError('provider response too large')
                result=json.loads(raw)
            if isinstance(result,dict) and (result.get('error') or result.get('Error')):
                raise ValueError('provider returned API error')
            if validate is not None: result=validate(result)
            self.failures[base]=0
            return result
        except Exception:
            self.failures[base]=self.failures.get(base,0)+1
            raise

    def rpc(self,base,method,params):
        def result(reply):
            if (not isinstance(reply,dict) or reply.get('jsonrpc')!='2.0'
                or type(reply.get('id')) is not int or reply['id']!=1 or reply.get('result') is None):
                raise ValueError('malformed RPC response')
            return reply['result']
        return self.request(base,payload={'jsonrpc':'2.0','id':1,'method':method,'params':params},validate=result)
